### ISSUE TITLE
Missing fa-exclamation icon

### ISSUE THREAD

**Issue by malcyL** [talis/Font-Talis#8]
AT-90 / PLAT-1099 specifies:

> Highlight the action menu and "Select platform" action (similar style to Critic) when one hasn't been selected.

I'm assuming we're talking about this I've just screenshoted from Critic:

![alert](https://user-images.githubusercontent.com/232529/28461192-5d5cceae-6e0d-11e7-9ef9-e789ad0127ef.png)

However, the fa-exclamation icon is missing from font talis - can we add it in please.

**Comment by jeremybaines** [comment]
Done! What good service!  :-)
